### PR TITLE
Update Chinese translation from Cemu 1.15.xx to 1.20.0c

### PR DESCRIPTION
**Pull request by Genglxy**
Cemu's Chinese translation has not been updated for a year and a half. During this time, Cemu has undergone a lot of changes. Half of the translations are missing, and a small number of translations have problems. I have been using Cemu for a year and I hope to contribute to the Cemu community and make it more convenient for users in China. Hope to pass, thank you~

### CODE REVIEW

**Comment by Fs00** [comment]
Thanks! I will review it in the next days.

**Comment by Genglxy** [comment]
> Thanks! I will review it in the next days.

Thanks a lot!

**Comment by Fs00** [comment]
As announced in #70, I've just pushed on the main repo the almost finished work done by the other translator some months ago (commit 35223aa, I've put in the message the issues the other translator didn't fix).
I think that the safest way to "rebase" your work is to start fresh by updating with the latest POT the current Chinese translation file and then copying one by one the new translations you made, replacing the existing ones if needed (I fear that by resolving conflicts manually we could miss some strings that have been moved around).

Sorry for creating extra work to you, but I would feel really bad throwing away the huge work made by the other translator. I should have handled this situation better.

**Comment by Genglxy** [comment]
> As announced in #70, I've just pushed on the main repo the almost finished work done by the other translator some months ago (commit [35223aa](https://github.com/TeamCemu/Cemu-Language/commit/35223aa3840eed558fe9095cad88288a8044d6ad), I've put in the message the issues the other translator didn't fix).
> I think that the safest way to "rebase" your work is to start fresh by updating with the latest POT the current Chinese translation file and then copying one by one the new translations you made, replacing the existing ones if needed (I fear that by resolving conflicts manually we could miss some strings that have been moved around).
> 
> Sorry for creating extra work to you, but I would feel really bad throwing away the huge work made by the other translator. I should have handled this situation better.

I understand that this is very complicated. In any case, everyone hopes that Cemu can become better. I have adjusted the translation on the basis of #49 , which involves some hard-to-find errors, such as full-width and half-width colons that will cause {:x} not to be recognized by the program, and some translation problems. I will resubmit a pull request.

**Pull request closed without merging**
