### PR TITLE
Update Chinese translation to 1.20.0c from 1.17.3 based on #49

### PR DESCRIPTION
**Pull request by Genglxy**
update content:
Fixed the bug of full-width half-width colon, which would cause {:x} to be unrecognized by the program.
I merged my previous translations with #49, partly based on them, and corrected a few incorrect expressions.
Fixed the problem of &.
Correct the layout, add spaces between Chinese and English, and add English contrast to the technical vocabulary with low frequency of use.
Add new translation content.
For Shader mul accuracy, since the exact translation of mul cannot be found, the original English text is used instead.

### CODE REVIEW

**Comment by Genglxy** [comment]
In addition, if you don't mind, I have attached the words "If you have any translation comments, please send to email xxx@xxx.com" in the getting started and General settings - Interface, because I have the willingness to maintain for a long time, and most Chinese players Will not use github.
If you think this is inappropriate, I can of course delete these clips.

**Comment by Genglxy** [comment]
Added: Note the following explanation, Shader mul accuracy has been translated into 着色器乘法精度(shader multiplication accuracy).

**Comment by Fs00** [comment]
I won't be able to merge this PR as it is, since your work has not been made on top of commit 35223aa.
As I said in #69, you need to "start fresh", that is to put your work in a new PO file that is created by updating the current zh.po (the one updated to 1.17.3) with the latest POT.
Then you need to put your PO in a clean fork (instead of deleting and recreating the fork you could move back your fork's master branch and then force push, if you are comfortable with Git), so that it doesn't conflict with your previous work.
Pardon me if I hasn't been clear enough in the first place.

**Comment by Fs00** [comment]
> In addition, if you don't mind, I have attached the words "If you have any translation comments, please send to email xxx@xxx.com" in the getting started and General settings - Interface, because I have the willingness to maintain for a long time, and most Chinese players Will not use github.

In general we don't allow this kind of edits. I understand your point, but this kind of thing should be done by Cemu devs (maybe they could add a link to this repo's GitHub issues as a way to report translation issues).

**Comment by Genglxy** [comment]
> I won't be able to merge this PR as it is, since your work has not been made on top of commit [35223aa](https://github.com/TeamCemu/Cemu-Language/commit/35223aa3840eed558fe9095cad88288a8044d6ad).
> As I said in #69, you need to "start fresh", that is to put your work in a new PO file that is created by updating the current zh.po (the one updated to 1.17.3) with the latest POT.
> Then you need to put your PO in a clean fork (instead of deleting and recreating the fork you could move back your fork's master branch and then force push, if you are comfortable with Git), so that it doesn't conflict with your previous work.
> Pardon me if I hasn't been clear enough in the first place.

Sorry, I'm not familiar with GitHub. The new translation was changed on the basis of #49, but I did't fork the new repository. I will resubmit it later.

**Comment by Genglxy** [comment]
> > In addition, if you don't mind, I have attached the words "If you have any translation comments, please send to email [xxx@xxx.com](mailto:xxx@xxx.com)" in the getting started and General settings - Interface, because I have the willingness to maintain for a long time, and most Chinese players Will not use github.
> 
> In general we don't allow this kind of edits. I understand your point, but this kind of thing should be done by Cemu devs (maybe they could add a link to this repo's GitHub issues as a way to report translation issues).

Okay, I can understand. I will delete these clips. Besides, can you consider choosing the UI language before opening cemu for the first time? Otherwise, the translation of getting started is largely unnecessary. I don't know if these should be told to you, but I don't know where to feed back this question.

**Comment by Fs00** [comment]
> Besides, can you consider choosing the UI language before opening cemu for the first time? Otherwise, the translation of getting started is largely unnecessary. I don't know if these should be told to you, but I don't know where to feed back this question.

I'm just the Italian translator and the one who reviews PRs made to this repo 😬. I totally agree with you on this point, I'll forward your feedback to Cemu devs.

**Comment by Genglxy** [comment]
> > Besides, can you consider choosing the UI language before opening cemu for the first time? Otherwise, the translation of getting started is largely unnecessary. I don't know if these should be told to you, but I don't know where to feed back this question.
> 
> I'm just the Italian translator and the one who reviews PRs made to this repo 😬. I totally agree with you on this point, I'll forward your feedback to Cemu devs.

Thanks a lot~

**Comment by Genglxy** [comment]
> I won't be able to merge this PR as it is, since your work has not been made on top of commit [35223aa](https://github.com/TeamCemu/Cemu-Language/commit/35223aa3840eed558fe9095cad88288a8044d6ad).
> As I said in #69, you need to "start fresh", that is to put your work in a new PO file that is created by updating the current zh.po (the one updated to 1.17.3) with the latest POT.
> Then you need to put your PO in a clean fork (instead of deleting and recreating the fork you could move back your fork's master branch and then force push, if you are comfortable with Git), so that it doesn't conflict with your previous work.
> Pardon me if I hasn't been clear enough in the first place.

Hello there! Sorry to interrupt you, but I noticed that the pull request #72  I submitted five days ago is still not merged. Is there any translation problem? If so, I will modify it. Or is there any other reason why it cannot be merged? Looking forward to your reply, thanks a lot~

**Comment by Fs00** [comment]
Will review it now! I have been busy throughout the week.

**Comment by Genglxy** [comment]
> Will review it now! I have been busy throughout the week.

I'm really sorry to disturb you! It's just that the lack of news makes me a little worried. Thank you for your hard work~

**Pull request closed without merging**
