### PR TITLE
Update Hungarian translation for 1.21.0

### PR DESCRIPTION
**Pull request by smileyhead**
I have one request, though: can I have some context for ‘Title checksum of {:08x}-{:08x}?’ I'm not sure of what the variables stand for.

### CODE REVIEW

**Comment by smileyhead** [comment]
In that case, the translation should be correct. Thanks, guys!

**Review by Fs00 — CHANGES_REQUESTED** [review]
Thanks! There are only some little things to fix.

**Comment by smileyhead** [comment]
> "wud" is an acronym too, do the same as "JSON"

I fixed these with one exception: the file select dialogues. I checked the standard format in Windows and applied it to the whole string. I suggest this be addressed in the English version too. (Maybe file formats in all strings should be formatted like this; with a full stop in front and in lowercase?)

image
image

**Comment by Fs00** [comment]
> I fixed these with one exception: the file select dialogues. I checked the standard format in Windows and applied it to both strings. I suggest this be addressed in the English version too.

Great! :ok_hand:  And yes, I think that @TeamCemu should address the format of those strings.

**Review by Fs00 — APPROVED** [review]

**Pull request merged**
